---
- name: Install and start Apache on RHEL 9 EC2 instance
  hosts: rhel9_ec2
  become: yes
  tasks:
    - name: Install Apache (httpd) package
      yum:
        name: httpd
        state: present
        update_cache: yes

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes
